### ISSUE TITLE
hpack fails to build as of 2.7.2 with TARGET=linux-glibc

### ISSUE THREAD

**Issue by idl0r** [haproxy/haproxy#2009]
### Detailed Description of the Problem

In 2.7.1 it was fine, in 2.7.2 it doesn't compile anymore.
Tested with GCC 11 and 12
It compiles when not specifying TARGET. TARGET linux-glibc fails.
I haven't looked further into it yet.

### Expected Behavior

hpack should compile

### Steps to Reproduce the Behavior

make -j1 V=1 TARGET=linux-glibc dev/hpack/decode dev/hpack/gen-enc dev/hpack/gen-rht

### What is your configuration?

```haproxy
N/A
```

### Output of `haproxy -vv`

```plain
N/A
```

### Last Outputs and Backtraces

```plain
<idl0r@odin:~/haproxy-2.7.2>
zsh/3 10030 % make -j1 V=1 TARGET=linux-glibc dev/hpack/decode dev/hpack/gen-enc dev/hpack/gen-rht
cc -Iinclude  -O2 -g -Wall -Wextra -Wundef -Wdeclaration-after-statement -Wfatal-errors -Wtype-limits -Wshift-negative-value -Wshift-overflow=2 -Wduplicated-cond -Wnull-dereference -fwrapv -Wno-address-of-packed-member -Wno-unused-label -Wno-sign-compare -Wno-unused-parameter -Wno-clobbered -Wno-missing-field-initializers -Wno-cast-function-type -Wno-string-plus-int -Wno-atomic-alignment     -DDEBUG_STRICT -DDEBUG_MEMORY_POOLS -DUSE_EPOLL  -DUSE_NETFILTER     -DUSE_POLL -DUSE_THREAD  -DUSE_BACKTRACE   -DUSE_TPROXY -DUSE_LINUX_TPROXY -DUSE_LINUX_SPLICE -DUSE_LIBCRYPT -DUSE_CRYPT_H  -DUSE_GETADDRINFO    -DUSE_ACCEPT4   -DUSE_SLZ -DUSE_CPU_AFFINITY -DUSE_TFO -DUSE_NS -DUSE_DL -DUSE_RT      -DUSE_PRCTL  -DUSE_THREAD_DUMP      -DUSE_SHM_OPEN  -DCONFIG_HAPROXY_VERSION=\"2.7.2-7e295dd\" -DCONFIG_HAPROXY_DATE=\"2023/01/20\" -c -o dev/hpack/decode.o dev/hpack/decode.c
In file included from include/../src/hpack-dec.c:35,
                 from dev/hpack/decode.c:87:
include/haproxy/global.h:52:35: error: thread-local declaration of 'trash' follows non-thread-local declaration
   52 | extern THREAD_LOCAL struct buffer trash;
      |                                   ^~~~~
compilation terminated due to -Wfatal-errors.
make: *** [Makefile:966: dev/hpack/decode.o] Error 1
```

**Comment by Darlelet** [comment]
Thanks for reporting

"global.h" header file dependency for `hpack-dec.c` has recently been introduced with 7d84439b4859915fd9dcfa9362109c402c867b96

`hpack-dec.c` being included in `dev/hpack/decode.c`:
global **trash** conflicts with local `decode.c` **trash** variable
```c
char trash_buf[MAX_RQ_SIZE];
char tmp_buf[MAX_RQ_SIZE];

struct buffer trash = { .area = trash_buf, .data = 0, .size = sizeof(trash_buf) };
struct buffer tmp   = { .area = tmp_buf,   .data = 0, .size = sizeof(tmp_buf)   };
```

**Comment by Darlelet** [comment]
As for why it compiles without linux-glibc TARGET:
USE_THREAD is defined for glibc target but not for default target.

adding THREAD_LOCAL to trash variable in `decode.c` seems to fix the issue.
(at least to restore original behavior)
```diff
diff --git a/dev/hpack/decode.c b/dev/hpack/decode.c
index ae825120f..13c95c77a 100644
--- a/dev/hpack/decode.c
+++ b/dev/hpack/decode.c
@@ -30,7 +30,7 @@ uint8_t buf[MAX_RQ_SIZE];
 char trash_buf[MAX_RQ_SIZE];
 char tmp_buf[MAX_RQ_SIZE];
 
-struct buffer trash = { .area = trash_buf, .data = 0, .size = sizeof(trash_buf) };
+THREAD_LOCAL struct buffer trash = { .area = trash_buf, .data = 0, .size = sizeof(trash_buf) };
 struct buffer tmp   = { .area = tmp_buf,   .data = 0, .size = sizeof(tmp_buf)   };
 
 /* displays a <len> long memory block at <buf>, assuming first byte of <buf>
```

**Comment by Darlelet** [comment]
Here is the redacted patch:
[0001-DEV-hpack-fix-trash-build-regression.patch.txt](https://github.com/haproxy/haproxy/files/10501099/0001-DEV-hpack-fix-trash-build-regression.patch.txt)

**Comment by idl0r** [comment]
Looks good. Thanks!

**Comment by wtarreau** [comment]
Merged and backported, thank you Aurélien! Closing now.

**Comment by idl0r** [comment]
@wtarreau FYI: It somehow didn't made it into 2.4.22.

**Comment by wtarreau** [comment]
Argh, indeed, you're right, I'm seeing that it's missing from both 2.5 and 2.4 :-(   The most annoying is that I have been very careful not to miss anything! It's really too hard to review one hundred patches spread over 7 branches at once...  I've just pushed them both to 2.5 and 2.4 now. Thanks for notifying me Christian!

**Comment by Darlelet** [comment]
My bad, I didn't see that https://github.com/haproxy/haproxy/commit/7d84439b4859915fd9dcfa9362109c402c867b96 was marked to be backported on all supported versions and thus did not explicitly mentioned that the fix should've been backported with it :(

**Comment by wtarreau** [comment]
No worries, shit happens from time to time. What matters is that we can fix it quickly enough.

**Comment by Darlelet** [comment]
It may be required for the 2.2 as well since https://github.com/haproxy/haproxy/commit/7d84439b4859915fd9dcfa9362109c402c867b96 was backported a few weeks ago

**Comment by wtarreau** [comment]
For me in 2.2 it builds fine so I concluded it was not needed.

**Comment by Darlelet** [comment]
Forget that, you're right dev/hpack is not included in 2.2

**Comment by wtarreau** [comment]
Great, thanks for the double check!
