### ISSUE TITLE
fedora ci fails due to recent changes in vtest action

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#3336]
### Detailed Description of the Problem

regression introduced in  https://github.com/chipitsine/haproxy/commit/64d6c91c90c08f9c232fdecf3f08c86be5cf9236

<img width="566" height="212" alt="Image" src="https://github.com/user-attachments/assets/1a330d89-636c-4f3b-b9da-f30538dc84ef" />

```
sysctl: permission denied on key "fs.suid_dumpable"
```

https://github.com/chipitsine/haproxy/actions/runs/24660508868/job/72104978570

### Expected Behavior

not to fail

### Steps to Reproduce the Behavior

run fedora rawhide workflow

### Do you have any idea what may have caused this?

https://github.com/chipitsine/haproxy/commit/64d6c91c90c08f9c232fdecf3f08c86be5cf9236

### What is your configuration?

```haproxy
n/a
```

### Output of `haproxy -vv`

```plain
n/a
```

### Last Outputs and Backtraces

```plain

```

**Comment by wlallemand** [comment]
The builds are fixed with https://github.com/haproxy/haproxy/commit/5b27329dbdf8f5e7df1b35c97d356fbc60cad2df and https://github.com/haproxy/haproxy/commit/1ddda8eb3b8f2a0102facf69bf8b3d6e9e24f691. However the reg-tests are failing for some reason on the 32bits version.

**Comment by chipitsine** [comment]
thank you!

I'll have a look at 32bit failures

**Comment by wlallemand** [comment]
@chipitsine this is an issue in HAProxy, we're investigating.

**Comment by chipitsine** [comment]
I decided to focus on missing vtest logs in case of fedora.
that is reproducible for my local fedora as well

**Comment by wlallemand** [comment]
This problem was probably introduced by 1ed2c9da ("REGTESTS: list all skipped tests including 'feature cmd' ones") it changes the way the logs are kept, it's possible that it does not cover all cases

**Comment by chipitsine** [comment]
well, by saying "to focus" I mean that it will likely happen within a week or so

**Comment by wlallemand** [comment]
No problem, it's unlikely that we will touch at this part in the meantime

**Comment by chipitsine** [comment]
from what I see, it looks like crxpto policy is not applied to 32bit openssl

**Comment by wlallemand** [comment]
seems weird to me, I thought it worked in the past for x86 but I don't have access to the history anymore.

**Comment by wlallemand** [comment]
I tested a branch based on the latest commit that passed on this job + the few CI fixes we had https://github.com/wlallemand/haproxy/tree/20260421-test-fedora-rawhide.yml and it does pass. So it means the crypto policy is the same for x86 and x86_64.

**Comment by chipitsine** [comment]
surprisingly, I enabled asan ... and it caught some null pointer deref

https://github.com/chipitsine/haproxy/actions/runs/24727720729/job/72333246761

```
In file included from include/haproxy/server.h:38,
                 from include/haproxy/connection.h:38,
                 from include/haproxy/mux_quic.h:10,
                 from src/mux_quic.c:1:
src/mux_quic.c: In function 'qcs_alert':
src/mux_quic.c:546:47: error: potential null pointer dereference [-Werror=null-dereference]
  546 |         tasklet_wakeup(qcs_sc(qcs)->wait_event.tasklet, state);
include/haproxy/task.h:426:33: note: in definition of macro 'tasklet_wakeup'
  426 |         _tasklet_wakeup_on(tl, (tl)->tid, DEFVAL(TASK_WOKEN_OTHER, ##__VA_ARGS__), MK_CALLER(WAKEUP_TYPE_TASKLET_WAKEUP, 0, 0))
      |                                 ^~
```

**Comment by chipitsine** [comment]
yet another "issue" caught after disabling null deref check

```
src/hlua.c: In function ‘hlua_socket_receive_yield’:
src/hlua.c:2991:20: error: ‘len1’ may be used uninitialized [-Werror=maybe-uninitialized]
 2991 |                 if (len1 > missing_bytes) {
      |                    ^
src/hlua.c:2907:16: note: ‘len1’ was declared here
 2907 |         size_t len1;
      |                ^~~~
src/hlua.c:2994:41: error: ‘len2’ may be used uninitialized [-Werror=maybe-uninitialized]
 2994 |                 } if (nblk == 2 && len1 + len2 > missing_bytes)
      |                                    ~~~~~^~~~~~
src/hlua.c:2909:16: note: ‘len2’ was declared here
 2909 |         size_t len2;
      |                ^~~~
src/hlua.c:3000:9: error: ‘blk1’ may be used uninitialized [-Werror=maybe-uninitialized]
 3000 |         luaL_addlstring(&socket->b, blk1, len1);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/hlua.c:2906:21: note: ‘blk1’ was declared here
 2906 |         const char *blk1;
      |                     ^~~~
src/hlua.c:3003:17: error: ‘blk2’ may be used uninitialized [-Werror=maybe-uninitialized]
 3003 |                 luaL_addlstring(&socket->b, blk2, len2);
      |                 ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/hlua.c:2908:21: note: ‘blk2’ was declared here
 2908 |         const char *blk2;
      |                     ^~~~
At top level:

```

**Comment by wlallemand** [comment]
So we finally discovered that it is a problem in the scheduler which only impacts 32-bit architectures.

**Comment by chipitsine** [comment]
I did have a look at "missing logs"

https://github.com/haproxy/haproxy/blob/master/scripts/run-regtests.sh#L406-L412

that code tries to detect whether test failed or passed.
if test was timed out (and thus killed), it is considered as "passed".

and there's no way to detect "timed out" tests (I could not find easy one).


I would keep all logs all time (there's cleanup in case of success at the end), but I'm not sure why that complicated machinery was initially created.

is keeping all logs (in case of failure) bad idea ?

**Comment by wlallemand** [comment]
I'm forking this to a new issue, would be simpler.
