### ISSUE TITLE
QUIC build is broken on current master

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1190]
build on Fedora 33 / gcc-10.2

```
src/quic_sock.c: In function ‘quic_session_accept’:
src/quic_sock.c:60:31: error: ordered comparison of pointer with integer zero [-Werror=extra]
   60 |  if (conn_xprt_start(cli_conn < 0))
      |                               ^
src/quic_sock.c:60:31: error: passing argument 1 of ‘conn_xprt_start’ makes pointer from integer without a cast [-Werror=int-conversion]
   60 |  if (conn_xprt_start(cli_conn < 0))
      |                      ~~~~~~~~~^~~
      |                               |
      |                               int
In file included from src/quic_sock.c:18:
include/haproxy/connection.h:94:54: note: expected ‘struct connection *’ but argument is of type ‘int’
   94 | static inline int conn_xprt_start(struct connection *conn)
      |                                   ~~~~~~~~~~~~~~~~~~~^~~~
include/haproxy/connection.h:80:14: error: null pointer dereference [-Werror=null-dereference]
   80 |  return (conn->flags & CO_FL_XPRT_READY);
      |          ~~~~^~~~~~~
include/haproxy/connection.h:98:36: error: null pointer dereference [-Werror=null-dereference]
   98 |  if (!conn_xprt_ready(conn) && conn->xprt && conn->xprt->start)
      |                                ~~~~^~~~~~
include/haproxy/connection.h:99:9: error: null pointer dereference [-Werror=null-dereference]
   99 |   ret = conn->xprt->start(conn, conn->xprt_ctx);
      |         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
include/haproxy/connection.h:102:15: error: null pointer dereference [-Werror=null-dereference]
  102 |   conn->flags |= CO_FL_XPRT_READY;
      |               ^~
include/haproxy/connection.h:102:15: error: null pointer dereference [-Werror=null-dereference]
  102 |   conn->flags |= CO_FL_XPRT_READY;
      |   ~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~
```

**Comment by chipitsine** [comment]
clang-11:

```
src/quic_sock.c:60:22: error: incompatible integer to pointer conversion passing 'int' to parameter of type 'struct connection *' [-Werror,-Wint-conversion]
        if (conn_xprt_start(cli_conn < 0))
                            ^~~~~~~~~~~~
include/haproxy/connection.h:94:54: note: passing argument to parameter 'conn' here
static inline int conn_xprt_start(struct connection *conn)
                                                     ^
1 error generated.
make: *** [Makefile:927: src/quic_sock.o] Error 1
```

**Comment by cognet** [comment]
Let's fix that as well :)
