### ISSUE TITLE
Issues compiling haproxy 2.6.1 on solaris / gcc-5.5

### ISSUE THREAD

**Issue by FireBurn** [haproxy/haproxy#1794]
### Detailed Description of the Problem

```
  CC      src/ssl_sample.o
In file included from include/haproxy/api.h:35:0,
                 from include/haproxy/regex-t.h:28,
                 from include/haproxy/pattern-t.h:28,
                 from include/haproxy/acl-t.h:25,
                 from include/haproxy/acl.h:25,
                 from src/ssl_sample.c:22:
include/haproxy/bug.h: In function 'ha_crash_now':
include/haproxy/bug.h:48:9: warning: unknown option after '#pragma GCC diagnostic' kind [-Wpragmas]
 #pragma GCC diagnostic ignored "-Wnull-dereference"
         ^
In file included from include/haproxy/server-t.h:37:0,
                 from include/haproxy/lb_map-t.h:26,
                 from include/haproxy/backend-t.h:30,
                 from include/haproxy/proxy-t.h:34,
                 from include/haproxy/obj_type.h:32,
                 from include/haproxy/connection.h:34,
                 from src/ssl_sample.c:27:
include/haproxy/queue-t.h: At top level:
include/haproxy/queue-t.h:43:8: error: redefinition of 'struct queue'
 struct queue {
        ^
compilation terminated due to -Wfatal-errors.
gmake: *** [src/ssl_sample.o] Error 1

```

I've bisected this to:

https://github.com/haproxy/haproxy/commit/eea3817a47586eb27340f37bd77be155c679f7a0

```
eea3817a47586eb27340f37bd77be155c679f7a0 is the first bad commit
commit eea3817a47586eb27340f37bd77be155c679f7a0
Author: Willy Tarreau <w@1wt.eu>
Date:   Fri Jun 18 09:21:22 2021 +0200

    MINOR: queue: create a new structure type "queue"
    
    This structure will be common to proxies and servers and will contain
    everything needed to handle their respective queues. For now it's only
    a tree head, a length and an index.

 include/haproxy/queue-t.h | 6 ++++++
 1 file changed, 6 insertions(+)
```

### Expected Behavior

This script used to build:

```
#!/bin/bash

# Run on udwas010, run the mvn command on one of the build hosts

PREFIX=${HOME}/haproxy
BUILD_DIR=${HOME}/build
PCRE_VERSION=8.45
LUA_VERSION=5.4.4
HAPROXY_VERSION=2.4.16
HAPROXY_BRANCH=${HAPROXY_VERSION:0:3}

rm -rf ${BUILD_DIR}

mkdir -p ${BUILD_DIR}

cd ${BUILD_DIR}

export PKG_CONFIG_PATH=${PREFIX}/lib/pkgconfig:${PKG_CONFIG_PATH}
export PATH=${HOME}/perl/bin:/opt/csw/bin:/usr/ccs/bin:/usr/ucb:${PATH}
export LD_LIBRARY_PATH=${PREFIX}/lib/:/opt/csw/lib:${LD_LIBRARY_PATH}
export CC=/opt/csw/bin/sparc-sun-solaris2.10-gcc-5.5

wget --no-check-certificate https://mirrors.gigenet.com/OSDN/sfnet/p/pc/pcre/pcre/${PCRE_VERSION}/pcre-${PCRE_VERSION}.tar.gz
wget --no-check-certificate https://www.lua.org/ftp/lua-${LUA_VERSION}.tar.gz
wget --no-check-certificate http://www.haproxy.org/download/${HAPROXY_BRANCH}/src/haproxy-${HAPROXY_VERSION}.tar.gz

gzip -d *.gz

# Compile PCRE

tar xf pcre-${PCRE_VERSION}.tar

cd pcre-${PCRE_VERSION}

./configure --disable-shared --enable-jit --enable-pcregrep-jit --prefix=${PREFIX}

gmake -j10

gmake install

cd ..

# Build Lua

rm -rf lua-${LUA_VERSION}

tar xf lua-${LUA_VERSION}.tar

cd lua-${LUA_VERSION}

sed 's#install -p#install#g' Makefile > Makefile.tmp

mv Makefile.tmp Makefile

gmake CFLAGS="-O3 -mcpu=ultrasparc -fPIE -D_FORTIFY_SOURCE=2 -fno-strict-aliasing" LDFLAGS="-Wl,-z,now -ltermcap" solaris

gmake install INSTALL_TOP=${PREFIX} INSTALL_LIB=${PREFIX}/lib

cd ..

# Compile Haproxy

rm -rf haproxy-${HAPROXY_VERSION}

tar xf haproxy-${HAPROXY_VERSION}.tar

cd haproxy-${HAPROXY_VERSION}

sed "s#-Wl,-Bstatic -lpcreposix -lpcre -Wl,-Bdynamic#-Bstatic -lpcreposix -lpcre#g" Makefile > Makefile.tmp

sed 's#-Wl,$(if $(EXPORT_SYMBOL),$(EXPORT_SYMBOL),--export-dynamic)##g' Makefile.tmp > Makefile.tmp2

sed 's#install -v#install#g' Makefile.tmp2 > Makefile

gmake \
  CC=/opt/csw/bin/sparc-sun-solaris2.10-gcc-5.5 \
  CFLAGS="-O3 -mcpu=ultrasparc \$(SPEC_CFLAGS) -fPIE -D_FORTIFY_SOURCE=2 -fno-strict-aliasing" \
  LDFLAGS="-Wl,-z,now -ltermcap" \
  TARGET=solaris \
  USE_GETADDRINFO=1 \
  USE_LUA=1 \
  LUA_LIB=${PREFIX}/lib \
  LUA_INC=${PREFIX}/include \
  LUA_LIB_NAME=lua \
  USE_TFO=1 \
  USE_ZLIB=1 \
  ZLIB_LIB=/usr/lib/sparcv9 \
  ZLIB_INC=/usr/include \
  USE_STATIC_PCRE=1 \
  USE_PCRE_JIT=1 \
  USE_OPENSSL=1 \
  USE_NS= \
  USE_MY_ACCEPT4=1 \
  USE_LIBCRYPT=1 \
  PREFIX=${PREFIX} \
  -j10

gmake install PREFIX=${PREFIX}

```

### Steps to Reproduce the Behavior

Use new haproxy

### What is your configuration?

```haproxy
Compiling
```

### Output of `haproxy -vv`

```plain
haproxy -vv
```

**Comment by chipitsine** [comment]
I'm afraid structure should be renamed, please see

https://github.com/skeeto/endlessh/issues/14
https://github.com/skeeto/endlessh/pull/17

**Comment by capflam** [comment]
It is the same issue as #2449. I'm closing because the other issue is more recent/active. Thanks !
