### ISSUE TITLE
Error compiling HAProxy for Prometheus

### ISSUE THREAD

**Issue by olttwa** [haproxy/haproxy#110]
## Output of `haproxy -vv` and `uname -a`

```
$ haproxy -vv

Doesn't apply as we cannot compile/install it

$ uname -a
Linux some-gcloud-vm 4.15.0-1024-gcp #25~16.04.2-Ubuntu SMP Tue Oct 30 14:14:10 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```

## What's the configuration?

```
No configuration
```

## Steps to reproduce the behavior

1. Follow the compilation steps here: https://www.haproxy.com/blog/haproxy-exposes-a-prometheus-metrics-endpoint/#compiling-haproxy-for-prometheus 

## Actual behavior

```
$ make TARGET=linux2628 USE_LUA=1 USE_OPENSSL=1 USE_PCRE=1 USE_ZLIB=1 USE_SYSTEMD=1 EXTRA_OBJS="contrib/prometheus-exporter/service-prometheus.o"

  CC      src/ev_poll.o
  CC      src/ev_epoll.o
...........................
  CC      src/mworker-prog.o
  CC      src/debug.o
src/debug.c: In function ‘ha_panic’:
src/debug.c:162:2: warning: ignoring return value of ‘write’, declared with attribute warn_unused_result [-Wunused-result]
  write(2, trash.area, trash.data);
  ^
  CC      src/wdt.o
  CC      contrib/prometheus-exporter/service-prometheus.o
contrib/prometheus-exporter/service-prometheus.c: In function ‘promex_dump_global_metrics’:
contrib/prometheus-exporter/service-prometheus.c:1372:30: error: ‘idle_pct’ undeclared (first use in this function)
     metric = mkf_u32(FN_AVG, idle_pct);
                              ^
contrib/prometheus-exporter/service-prometheus.c:1372:30: note: each undeclared identifier is reported only once for each function it appears in
Makefile:830: recipe for target 'contrib/prometheus-exporter/service-prometheus.o' failed
make: *** [contrib/prometheus-exporter/service-prometheus.o] Error 1
```

## Expected behavior

`make TARGET=linux2628 USE_LUA=1 USE_OPENSSL=1 USE_PCRE=1 USE_ZLIB=1 USE_SYSTEMD=1 EXTRA_OBJS="contrib/prometheus-exporter/service-prometheus.o"` should work fine

## Do you have any idea what may have caused this?

This might be the error:

```
contrib/prometheus-exporter/service-prometheus.c:1372:30: error: ‘idle_pct’ undeclared (first use in this function)
     metric = mkf_u32(FN_AVG, idle_pct);
```

## Do you have an idea how to solve the issue?

no.

**Comment by lukastribus** [comment]
Which exact haproxy release is this?

**Comment by TimWolla** [comment]
@lukastribus It can be reproduced with the current “master”: `make -j4 TARGET=linux2628 EXTRA_OBJS="contrib/prometheus-exporter/service-prometheus.o"`

**Comment by TimWolla** [comment]
This issue was introduced in 81036f273824704ed0038de94f46101b9af1d61b:

```
[timwolla@/s/haproxy ((81036f27…)|BISECTING) [2]]g bisect bad           16:49:30
81036f273824704ed0038de94f46101b9af1d61b is the first bad commit
commit 81036f273824704ed0038de94f46101b9af1d61b
Author: Willy Tarreau <w@1wt.eu>
Date:   Mon May 20 19:24:50 2019 +0200

    MINOR: time: move the cpu, mono, and idle time to thread_info
    
    These ones are useful across all threads and would be better placed
    in struct thread_info than thread-local. There are very few users.

:040000 040000 86f689dc905d530e0f9932d0cfc9de7e77a06d71 bdff06f390139dbf1c488af6adcdf42d4907254b M	include
:040000 040000 4e7d13771eac53a2f112a6f18596c97c08f89c0e 02589a4d2ddf19b598393879564caa21c75286ab M	src
```

**Comment by lukastribus** [comment]
Thanks, so this is not something that affects release branches.

**Comment by chipitsine** [comment]
should we add `EXTRA_OBJS="contrib/prometheus-exporter/service-prometheus.o"` to some travis-ci build ? (not sure we need to add to all builds)

**Comment by wtarreau** [comment]
@chipitsine we could, it's like device detection in fact, they're all optional stuff that we're not used to build by default and that we should. The prometheus exporter builds very fast, I've updated my local build script to include it now, and we could add it to watch if we break it again. It's likely that in early dev stages such stuff would have to be disabled because it would break from time to time, and if it's in contrib, it's precisely because it's not the primary focus and should not slow down the rest of the development. But late in the dev cycle everything should start to cool down and to build fine.
