### ISSUE TITLE
Haproxy v2.0.9 build fails if OpenSSL's deprecated APIs are not used

### ISSUE THREAD

**Issue by val-kulkov** [haproxy/haproxy#367]
@EmericBr :

If OpenSSL's deprecated APIs are disabled (i.e., OpenSSL is compiled with the "no-deprecated" switch) haproxy v2.0.9 build fails:
```
ld: src/ssl_sock.o: in function `ssl_sock_prepare_ctx': ssl_sock.c:(.text+0xc558): undefined reference to `SSL_CTX_set_ecdh_auto'
```

The reference to SSL_CTX_set_ecdh_auto was introduced by commit a9363eb6a5. Instead, it should probably have been a no-op because the ECDH support is always enabled since OpenSSL 1.1.0. This is a quote from OpenSSL's CHANGES file:

>   *) SSL_{CTX_}set_ecdh_auto() has been removed and ECDH is support is
>      always enabled now.  If you want to disable the support you should
>      exclude it using the list of supported ciphers. This also means that the
>      "-no_ecdhe" option has been removed from s_server.
>      [Kurt Roeckx]

**Comment by chipitsine** [comment]
btw, I thought whether to include or not `no-deprecated` to travis-ci build
is it valid usecase ?

how did you get openssl built that way?

**Comment by chipitsine** [comment]
do you build haproxy for openwrt ?

**Comment by val-kulkov** [comment]
My haproxy build is part of a larger build, [OpenWRT](https://github.com/openwrt), which has an option to disable deprecated OpenSSL APIs.

**Comment by chipitsine** [comment]
just curious, how is openwrt is supposed to be used as load balancer ? it is usually pretty low on RAM/CPU/...

can you give some examples ?

**Comment by chipitsine** [comment]
@val-kulkov , what do you think, is it enough if we will switch ALL travis-ci builds to `no-deprecated` ? or we should leave both default and `no-deprecated` builds (i.e. increase build matrix size) ?

**Comment by wtarreau** [comment]
On Mon, Nov 18, 2019 at 10:23:39AM -0800, Ilya Shipitsin wrote:
> just curious, how is openwrt is supposed to be used as load balancer ? it is
> usually pretty low on RAM/CPU/...

It's quite convenient to route incoming traffic to HTTP/SSH depending on
what is detected. It's still possible to get a small build, consuming
little CPU and RAM. By not enabling threads it already shrinks quite a
bit.

Willy

**Comment by chipitsine** [comment]
I used to use openwrt, simple tasks like port forwarding are managed by iptables out of box )) But, I never needed to load balance between several incoming http/ssh in my home openwrt setup

**Comment by val-kulkov** [comment]
@chipitsine : OpenWRT is indeed designed to minimize resource use, including RAM and NVRAM. But it can also be installed and run on a more advanced hardware. Many modern routers now provide 1 GB or more of RAM and they have dual-core or quad-core CPUs. OpenWRT can be used on modern Raspberry PIs and x86-based SBCs.

OpenWRT is quite good for a router of a home or small office network. Many useful things are supported right out of the box. For example, integrating two networks via a Wireguard VPN is a breeze in OpenWRT these days. 802.11r support is now built-in by default. haproxy on OpenWRT can be useful where one runs a few webservers behind the firewall for example.

IMO, enabling "no-deprecated" by default will likely cause more problems to come to the surface, not just SSL_CTX_set_ecdh_auto. Someone who has the knowledge and the time has to look into this more closely I think.

**Comment by chipitsine** [comment]
@val-kulkov , I played with `no-deprecated` build earlier (but I was not sure it is valid case). weird, some extra headers must be included in case of openssl-1.0.2 (it works without those headers in default build). patch is pretty small.

actually, I asked whether `no-deprecated` builds are also include current builds. Or do we need to test both of them (thus build matrix will grow)

**Comment by lukastribus** [comment]
This is not just one single build issue, `no-deprecated` openssl support is simply not implemented. Once you fix this specific issue, you will uncover tons of other build issues - and no, this will certainly not guarantee compatibility with openssl 3.0.

Someone would have to be willing to invest a lot of time to dig through this and come up with a patch that preferably doesn't make the code completely unreadable. Only to then do it all over again in one year, when openssl 3.0 will be released.

**Comment by chipitsine** [comment]
well, openssl-3.0 is another big question. I did some builds, currently haproxy works with openssl-3.0 (in its default build), I think I will add it to travis soon.

things might change in the future, one day haproxy can break openssl-3.0 compatibility (or it can happen in `no-deprecated` or `--api=3.0.0` modes)

**Comment by wtarreau** [comment]
> one day haproxy can break openssl-3.0 compatibility

This is then a perfect reason for adding it now so that we know when
and hopefully what breaks it.

Thanks!
Willy

**Comment by chipitsine** [comment]
anyway, if someone have time and will to resolve `no-deprecated` issues:

https://travis-ci.com/chipitsine/haproxy/builds/137070577

(maybe, I'll address those issues in a week or so)


openssl-1.0.2

```
src/ssl_sock.o: In function `__ssl_sock_init':

ssl_sock.c:(.text.startup+0x90): undefined reference to `CRYPTO_set_id_callback'

src/ssl_sock.o: In function `__ssl_sock_deinit':

ssl_sock.c:(.text.exit+0x25): undefined reference to `ERR_remove_state'
```

openssl-1.1.X

```
ssl_sock.c:(.text+0x18b9): undefined reference to `X509_get_notBefore'

ssl_sock.c:(.text+0x18db): undefined reference to `X509_get_notAfter'

src/ssl_sock.o: In function `ssl_sock_prepare_ctx':

ssl_sock.c:(.text+0x3eeb): undefined reference to `SSL_CTX_set_ecdh_auto'

src/ssl_sock.o: In function `smp_fetch_ssl_x_notafter':

ssl_sock.c:(.text+0xc3b4): undefined reference to `X509_get_notAfter'

src/ssl_sock.o: In function `smp_fetch_ssl_x_notbefore':

ssl_sock.c:(.text+0xc4f4): undefined reference to `X509_get_notBefore'
```

**Comment by wtarreau** [comment]
Do we have a reliable way to know whether or not the deprecated API is included or not ? If there is at least one define, we can probably deal with all of these in the compat layer. Otherwise it may be fun only at the beginning :-/

**Comment by val-kulkov** [comment]
@wtarreau : [OpenSSL Wiki](https://wiki.openssl.org/index.php/OpenSSL_1.1.0_Changes) says

> The include files support setting the OPENSSL_API_COMPAT define that will hide functions that are deprecated in the selected version. To select the 1.1.0 version use -DOPENSSL_API_COMPAT=0x10100000L.

I take it to mean that setting -DOPENSSL_API_COMPAT=0x10100000L will hide all functions that are deprecated in 1.1.0. Therefore, the deprecated API is excluded.

**Comment by ehocdet** [comment]
It's more a subject to cleanup code than add new #ifdef.
X509_get_notAfter/X509_get_notBefore compatibility already done in dev branch.
SSL_CTX_set_ecdh_auto part is about remove useless code (deprecated because do nothing).
ERR_remove_state replaced by ERR_clear_error.
CRYPTO_set_id_callback  deprecated because do nothing.

**Comment by chipitsine** [comment]
hello @ehocdet , @wtarreau 

I did have a look at it during weekend.

`CRYPTO_set_id_callback` is called inside `ifdef`

https://github.com/haproxy/haproxy/blob/master/src/ssl_sock.c#L311-L354

somehow, seems `defined(USE_THREAD) && (HA_OPENSSL_VERSION_NUMBER < 0x10100000L)` is true if openssl is built in `no-deprecated` mode, but I could not find why

**Comment by wtarreau** [comment]
Strange. This would mean that it would not report the same openssl version, which sounds odd to me.

**Comment by chipitsine** [comment]
I will have a look next weekend. I just wanted to share my findings in hope they could save time for you

**Comment by ehocdet** [comment]
perhaps is link to
`HA_OPENSSL_VERSION_NUMBER < 0x10100000L` 
should be:
`HA_OPENSSL_VERSION_NUMBER < 0x1010000fL`

**Comment by chipitsine** [comment]
I sent patch to list

https://www.mail-archive.com/haproxy@formilux.org/msg35511.html

**Comment by lukastribus** [comment]
Fixes b3814c2ca8 and a26d1e13 have been committed back in December and are in 2.0.12 as well as in 2.1.2.

Closing.
