### ISSUE TITLE
Lua-Api documentation & Redis-lua

### ISSUE THREAD

**Issue by msempere** [haproxy/haproxy#43]
Hi,
I've been checking the documentation: doc/lua-api/index.rst
where there is an example on how to use the new lua functionality with Redis in Haproxy.

This library (Redis-Lua) depends on luasocket, that only works with Lua 5.1 and not 5.3.
Is it possible to run Haproxy with Lua 5.1 or 5.3 only?
If it's 5.3 only, that seems, then, Redis-Lua is not possible to use with Haproxy.

**Comment by msempere** [comment]
Ok, Haproxy only works with Lua 5.3.
From the output when trying to compile with Lua 5.1:

src/hlua.c:11:2: error: #error "Requires Lua 5.3 or later."

That means Haproxy cannot use Redis-Lua.
