### ISSUE TITLE
QUIC: potential null pointer deref

### ISSUE THREAD

**Issue by chipitsine** [haproxy/haproxy#1454]
### Tool Name and Version

gcc

### Code Report

```plain
https://github.com/chipitsine/haproxy/runs/4170112595?check_suite_focus=true


 In file included from include/haproxy/connection.h:28,
                 from src/quic_sock.c:18:
src/quic_sock.c: In function ‘quic_sock_fd_iocb’:
include/haproxy/buf.h:303:9: error: potential null pointer dereference [-Werror=null-dereference]
  303 |  left = b_size(b) - left;
      |         ^~~~~~~~~
include/haproxy/buf.h:301:18: error: potential null pointer dereference [-Werror=null-dereference]
  301 |  left  = right + b_data(b);
      |                  ^~~~~~~~~
include/haproxy/buf.h:170:9: error: potential null pointer dereference [-Werror=null-dereference]
  170 |  return __b_head_ofs(b);
      |         ^~~~~~~~~~~~~~~
cc1: all warnings being treated as errors
```
```


### Additional Information

_No response_

### Output of `haproxy -vv`

```plain
not built
```

**Comment by haproxyFred** [comment]
I can reproduce this compilation issue only if I revert c4becf5 which should fix it.
Which version of GCC do you use?

**Comment by chipitsine** [comment]
the one shipped with Ubuntu 20.04.3

![image](https://user-images.githubusercontent.com/2217296/142608925-a5b87b84-79ff-472b-a26d-ef96e95f3747.png)

I believe it is gcc11, but also may include some patches/options when packaging

**Comment by TimWolla** [comment]
> I believe it is gcc11, but also may include some patches/options when packaging

gcc 9 according to my local Ubuntu 20.04:

```
$ cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"
$ gcc --version
gcc (Ubuntu 9.4.0-1ubuntu1~20.04) 9.4.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by chipitsine** [comment]
indeed, sorry for buzz, I was wrong

![image](https://user-images.githubusercontent.com/2217296/142617878-e57fe429-580f-454a-90bf-827c00429b03.png)

**Comment by haproxyFred** [comment]
I do not understand. How can haproxy -vv be run if haproxy cannot be built? Have I missed something?

**Comment by chipitsine** [comment]
There are many builds on Ubuntu, I took other build (with stock ssl)

**Comment by a-denoyelle** [comment]
I can reproduce by using the ubuntu docker image 20.04. I'm looking for
a fix...

-- 
Amaury Denoyelle

**Comment by a-denoyelle** [comment]
I have push a fix (I referenced by mistake the previous issue #1445).
Now let's hope it should be good to compile haproxy with QUIC on ubuntu LTS. @chipitsine can you reexecute your CI so we can see the result ? Thanks.

**Comment by TimWolla** [comment]
> I have push a fix (I referenced by mistake the previous issue

For reference: ee72a43321a22719eb06a6fad5240039aeb70b04

**Comment by chipitsine** [comment]
I confirm fixed QUICTLS
https://github.com/chipitsine/haproxy/runs/4266847608?check_suite_focus=true
