### ISSUE TITLE
Build error: `proto_sockpair.c: error: variable-sized object may not be initialized except with an empty initializer`

### ISSUE THREAD

**Issue by barracuda156** [haproxy/haproxy#3226]
### Detailed Description of the Problem

```
  CC      src/proto_sockpair.o
  CC      src/raw_sock.o
src/proto_sockpair.c: In function 'send_fd_uxst':
src/proto_sockpair.c:246:49: error: variable-sized object may not be initialized except with an empty initializer
  246 |         char cmsgbuf[CMSG_SPACE(sizeof(int))] = {0};
      |                                                 ^
src/proto_sockpair.c:247:45: error: variable-sized object may not be initialized except with an empty initializer
  247 |         char buf[CMSG_SPACE(sizeof(int))] = {0};
      |                                             ^
At top level:
cc1: note: unrecognized command-line option '-Wno-atomic-alignment' may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option '-Wno-string-plus-int' may have been intended to silence earlier diagnostics
make: *** [src/proto_sockpair.o] Error 1
make: *** Waiting for unfinished jobs....
```

### Expected Behavior

Build should succeed as before. (At least 3.0.3 was building just fine.)

### Steps to Reproduce the Behavior

`sudo port -v build haproxy`

### Do you have any idea what may have caused this?

The bug was introduced by https://github.com/haproxy/haproxy/commit/10c14a1ed049707854614f28cd57e5fd43ec3b31 

### What is your configuration?

```haproxy
macOS 10.6.8
gcc 14.3.0
```

### Output of `haproxy -vv`

```plain
3.3.0
```

### Last Outputs and Backtraces

```plain

```

### Additional Information

FYI @einval22 @wlallemand

**Comment by wtarreau** [comment]
This means that CMSG_SPACE() is not defined on your system. On linux it's in sys/socket.h, which is included in this file. Can you check "man CMSG_SPACE" or possibly "man recvmsg" to see what is suggested on your system ? I'm also a bit surprised since we systematically build on macos as part of the CI without facing any issues. Are you aware of anything specific about your system ?

**Comment by barracuda156** [comment]
@wtarreau Thank you. The macro exists: https://github.com/alexey-lysiuk/macos-sdk/blob/78bd32056afc9a4720580f82d4ac839e7e831b6e/MacOSX10.6.sdk/usr/include/sys/socket.h#L559
Perhaps, `_POSIX_C_SOURCE` (or `_XOPEN_SOURCE`) flag is passed by the build and that makes it unavailable.
`_DARWIN_C_SOURCE` should fix that, if that is the issue.

**Comment by wtarreau** [comment]
OK. Does it work if you add "DEFINE+=-D_DARWIN_C_SOURCE" on your "make" command line ? Alternately you could also add `#define _DARWIN_C_SOURCE` in proto_sockpair.c before the include line for sys/socket.h and see if it helps.

What is strange is that other files like cli.c use this macro and don't define anything. A few files like ssl_sock.c do use it as well but they define _GNU_SOURCE. It's possible that on your platform, _GNU_SOURCE automatically defines _DARWIN_C_SOURCE. So you may also try to define _GNU_SOURCE at the top of proto_sockpair.c to see if it helps. This would make things consistent with other files.

**Comment by barracuda156** [comment]
Just tried, it still fails with `-D_DARWIN_C_SOURCE` flag passed. I do not see `-D_POSIX_C_SOURCE` anyway, so looks like the issue is elsewhere.

**Comment by wtarreau** [comment]
Well, I know absolutely nothing about macOS versions, but from what I'm seeing here: https://github.com/haproxy/haproxy/actions/runs/20399806733/job/58620512632 we're building on macOS 26.0.1 with clang. Is it possible that your version 10 is far too old ? I doubt it since gcc-14.3 is somewhat recent.

Could you check if you can build ssl_sock.o ? Just pass `src/ssl_sock.o` at the end of your "make" command line while keeping other options.

**Comment by wtarreau** [comment]
I found a reference to an old page of OSX indicating that older versions needed to have sys/types.h included before sys/socket.h. Could you try moving that include before it just in case ?

**Comment by barracuda156** [comment]
> Could you check if you can build ssl_sock.o ?

Everything else in `haproxy` 3.3.0 built fine. The only change it needed was to revert 10c14a1ed049707854614f28cd57e5fd43ec3b31 commit. So whatever causes the error, it does not affect other source files.

> I found a reference to an old page of OSX indicating that older versions needed to have sys/types.h included before sys/socket.h. Could you try moving that include before it just in case?

Some headers need `sys/socket.h` before them (I recall, `netinet` ones), but `sys/types.h` is already included at the top of `sys/socket.h`, so that one is unnecessary.

https://github.com/alexey-lysiuk/macos-sdk/blob/78bd32056afc9a4720580f82d4ac839e7e831b6e/MacOSX10.6.sdk/usr/include/sys/socket.h#L75

**Comment by wtarreau** [comment]
OK. Then I'm afraid that I'll have to let you dig since this issue only happens on your system with this specific file and nobody else reported it, so it looks like you're the only one with the ability to debug it :-/

**Comment by barracuda156** [comment]
@wtarreau Ok, I have found the same error:

https://github.com/ElementsProject/lightning/issues/6910
https://github.com/aws/s2n-tls/issues/4673

Not sure if a bug in SDK or elsewhere, but we may have a fix for it.

**Comment by wtarreau** [comment]
So it would be their DARWIN_ALIGN32 macro definition that's causing all this mess ? Well, then let's just let the compiler think it's a VLA if it wants, and move to memset. Could you please try the attached patch ?

[p.diff.txt](https://github.com/user-attachments/files/24287134/p.diff.txt)

**Comment by wlallemand** [comment]
Any update on this?

**Comment by barracuda156** [comment]
Sorry for a delay, I will try.

**Comment by barracuda156** [comment]
@wlallemand @wtarreau Yes, the patch from https://github.com/haproxy/haproxy/issues/3226#issuecomment-3680908468 works for me.

Upd2. All good, confirmed.

**Comment by wtarreau** [comment]
OK thank you very much! We'll merge it then.

**Comment by wtarreau** [comment]
Now merged in -dev, will be backported.
