### ISSUE TITLE
Issues with statically built haproxy

### ISSUE THREAD

**Issue by FireBurn** [haproxy/haproxy#1775]
### Detailed Description of the Problem

Statically built haproxy on RHEL5 runs well on RHEL6 on versions 2.4.17, 2.5.7 however doesn't build on 2.5.0 and fails to execute on 2.6.1

When it does execute I get the following:

```
./haproxy -vvv
Memory fault(coredump)
```

```
gdb --args haproxy -vvv
GNU gdb (GDB) Red Hat Enterprise Linux (7.2-92.el6)
Copyright (C) 2010 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /apps/was/haproxy...(no debugging symbols found)...done.
(gdb) start
Temporary breakpoint 1 at 0x59f4c0
Starting program: /apps/was/haproxy -vvv

Temporary breakpoint 1, 0x000000000059f4c0 in main ()
(gdb) cont
Continuing.

Program received signal SIGSEGV, Segmentation fault.
0x000000000097563d in call_dl_lookup ()
(gdb) bt
#0  0x000000000097563d in call_dl_lookup ()
#1  0x00000000009715a6 in _dl_catch_error ()
#2  0x0000000000975832 in do_sym ()
#3  0x0000000000945224 in dlsym_doit ()
#4  0x00000000009715a6 in _dl_catch_error ()
#5  0x0000000000945541 in _dlerror_run ()
#6  0x00000000009451e6 in __dlsym ()
#7  0x0000000000613a2d in init_pools ()
#8  0x000000000059f575 in main ()
```

I can build 2.6.1 statically on RHEL8 which runs on RHEL7, but not RHEL6 as the kernel is too old

I've tried bisecting where it breaks but there are a lot of (probably unrelated) build failures:

```
src/freq_ctr.c: In function ‘freq_ctr_total’:
src/freq_ctr.c:34: error: assignment of read-only variable ‘ret’
src/freq_ctr.c:35: error: assignment of read-only variable ‘ret’
src/freq_ctr.c:36: error: assignment of read-only variable ‘ret’
src/freq_ctr.c:50: error: assignment of read-only variable ‘ret’
src/freq_ctr.c:57: error: assignment of read-only variable ‘ret’
src/freq_ctr.c:61: error: assignment of read-only variable ‘ret’
src/freq_ctr.c:70: error: assignment of read-only variable ‘ret’
src/freq_ctr.c:72: error: assignment of read-only variable ‘ret’
src/freq_ctr.c:74: error: assignment of read-only variable ‘ret’
make: *** [src/freq_ctr.o] Error 1
make: *** Waiting for unfinished jobs....
```

Which was caused by:

```
55a0975b1e957e9e23df8d9dd5400b40455c3fa9 is the first bad commit
commit 55a0975b1e957e9e23df8d9dd5400b40455c3fa9
Author: Willy Tarreau <w@1wt.eu>
Date:   Thu Jul 15 15:45:44 2021 +0200

    BUG/MINOR: freq_ctr: use stricter barriers between updates and readings
    
    update_freq_ctr_period() was using relaxed atomics without using barriers,
    which usually works fine on x86 but not everywhere else. In addition, some
    values were read without being enclosed by barriers, allowing the compiler
    to possibly prefetch them a bit earlier. Finally, freq_ctr_total() was also
    reading these without enough barriers. Let's make explicit use of atomic
    loads and atomic stores to get rid of this situation. This required to
    slightly rearrange the freq_ctr_total() loop, which could possibly slightly
    improve performance under extreme contention by avoiding to reread all
    fields.
    
    A backport may be done to 2.4 if a problem is encountered, but last tests
    on arm64 with LSE didn't show any issue so this can possibly stay as-is.

 include/haproxy/freq_ctr.h | 24 +++++++++----------
 src/freq_ctr.c             | 58 +++++++++++++++++++++++++++++++---------------
```

### Expected Behavior

haproxy to not abort

### Steps to Reproduce the Behavior

haproxy -vvv

### What is your configuration?

```haproxy
Building a static haproxy including libz, openssl, pcre2, lua
```

### Output of `haproxy -vv`

```plain
N/A
```

**Comment by FireBurn** [comment]
It looks like that later bug was fixed with:

```
commit a65b4933bae485c7dd7de53c665d09954f92a9f9
Author: Willy Tarreau <w@1wt.eu>
Date:   Fri Jan 28 09:10:52 2022 +0100

    BUILD: cpuset: do not use const on the source of CPU_AND/CPU_ASSIGN
    
    The man page indicates that CPU_AND() and CPU_ASSIGN() take a variable,
    not a const on the source, even though it doesn't make much sense. But
    with older libcs, this triggers a build warning:
    
      src/cpuset.c: In function 'ha_cpuset_and':
      src/cpuset.c:53: warning: initialization discards qualifiers from pointer target type
      src/cpuset.c: In function 'ha_cpuset_assign':
      src/cpuset.c:101: warning: initialization discards qualifiers from pointer target type
    
    Better stick stricter to the documented API as this is really harmless
    here. There's no need to backport it (unless build issues are reported,
    which is quite unlikely).
```

**Comment by FireBurn** [comment]
And also:

```
commit 8da23393a1ec3f24dcd408f4b35fdd3d9a141a5f
Author: Willy Tarreau <w@1wt.eu>
Date:   Fri Jan 28 08:52:57 2022 +0100

    BUILD: atomic: make the old HA_ATOMIC_LOAD() support const pointers
    
    We have an implementation of atomic ops for older versions of gcc that
    do not provide the __builtin_* API (< 4.4). Recent changes to the pools
    broke that in pool_releasable() by having a load from a const pointer,
    which doesn't work there due to a temporary local variable that is
    declared then assigned. Let's make use of a compount statement to assign
    it a value when declaring it.
    
    There's no need to backport this.
```

**Comment by FireBurn** [comment]
So that was a pain but the first bad commit was:

```
ed232148a7dbffbc279cb8efde3fd32c3fa94847 is the first bad commit
commit ed232148a7dbffbc279cb8efde3fd32c3fa94847
Author: David Carlier <devnexen@gmail.com>
Date:   Thu Nov 25 16:09:45 2021 +0000

    MEDIUM: pool: refactor malloc_trim/glibc and jemalloc api addition detections.
    
    Attempt to detect jemalloc at runtime before hand whether linked or via
    symbols overrides, and fall back to malloc_trim/glibc for Linux otherwise.

 src/pool.c | 62 ++++++++++++++++++++++++++++++++------------------------------
 1 file changed, 32 insertions(+), 30 deletions(-)
```

**Comment by FireBurn** [comment]
On closer inspection, whilst "haproxy -vvv" works on RHEL7 as soon as the application is loaded it aborts:

```
gdb --args /apps/was/haproxy/bin/haproxy -D -f /apps/haproxy/etc/ -p /apps/haproxy/bin/n01.pid
GNU gdb (GDB) Red Hat Enterprise Linux 7.6.1-120.el7
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-redhat-linux-gnu".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>...
Reading symbols from /apps/was/haproxy/bin/haproxy...done.
(gdb) start
Temporary breakpoint 1 at 0x63faa3: file src/haproxy.c, line 3006.
Starting program: /apps/haproxy/bin/haproxy -D -f /apps/haproxy/etc/ -p /apps/haproxy/bin/n01.pid

Temporary breakpoint 1, main (argc=6, argv=0x7fffffffdbc8) at src/haproxy.c:3006
3006	{
(gdb) cont
Continuing.
warning: the debug information found in "/usr/lib/debug//lib64/libc-2.17.so.debug" does not match "/lib64/libc.so.6" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug/usr/lib64/libc-2.17.so.debug" does not match "/lib64/libc.so.6" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug//usr/lib64/libc-2.17.so.debug" does not match "/lib64/libc.so.6" (CRC mismatch).

warning: the debug information found in "/usr/lib/debug/usr/lib64//libc-2.17.so.debug" does not match "/lib64/libc.so.6" (CRC mismatch).

Missing separate debuginfo for /lib64/libc.so.6
Try: yum --enablerepo='*debug*' install /usr/lib/debug/.build-id/fc/4fa58e47a5acc137eadb7689bce4357c557a96.debug
haproxy: dl-call-libc-early-init.c:37: _dl_call_libc_early_init: Assertion `sym != NULL' failed.

Program received signal SIGABRT, Aborted.
0x0000000000767caf in raise ()
(gdb) bt
#0  0x0000000000767caf in raise ()
#1  0x00000000004011c8 in abort ()
#2  0x000000000040109c in __assert_fail_base.cold.0 ()
#3  0x0000000000b050b6 in __assert_fail ()
#4  0x0000000000b955f3 in _dl_call_libc_early_init ()
#5  0x0000000000b9358c in dl_open_worker_begin ()
#6  0x0000000000b991b4 in _dl_catch_exception ()
#7  0x0000000000b92d00 in dl_open_worker ()
#8  0x0000000000b991b4 in _dl_catch_exception ()
#9  0x0000000000b92f27 in _dl_open ()
#10 0x0000000000b979e6 in do_dlopen ()
#11 0x0000000000b991b4 in _dl_catch_exception ()
#12 0x0000000000b99273 in _dl_catch_error ()
#13 0x0000000000b97a27 in dlerror_run ()
#14 0x0000000000b97ea9 in __libc_dlopen_mode ()
#15 0x0000000000b87721 in __nss_lookup_function ()
#16 0x0000000000b877e0 in __nss_lookup ()
#17 0x0000000000b75c5b in getpwnam_r ()
#18 0x0000000000b75860 in getpwnam ()
#19 0x00000000006c8b27 in cfg_parse_global (file=0x1191d60 "/apps/haproxy/etc//0-haproxy.cfg", linenum=4, args=0x7fffffffd3e0, kwm=0) at src/cfgparse-global.c:560
#20 0x00000000005aab89 in readcfgfile (file=0x1191d60 "/apps/haproxy/etc//0-haproxy.cfg") at src/cfgparse.c:2169
#21 0x000000000063ccd8 in init (argc=6, argv=0x7fffffffdbc8) at src/haproxy.c:2013
#22 0x000000000063fe22 in main (argc=6, argv=0x7fffffffdbc8) at src/haproxy.c:3069
```

**Comment by wtarreau** [comment]
It looks as if you were having trouble in some libraries. Haproxy is only trying to resolve an /etc/passwd entry using getpwnam() and it results in opening gobs of libs via dlopen() and crashing as if there was an unexpected condition (e.g. expected library not found, etc).

Normally when you try to build statically, glibc issues a warning at link time that certain functions like getpwnam() may fail. I've been used to seeing them fail soft (i.e. impossibility to resolve user names and host names), but not via a crash. Admittedly I don't use full static builds often, in part due to this. glibc really needs to be dynamically linked nowadays for these parts to work.

What's the reason why you're building statically ? Because you do it from another machine with a more recent glibc, maybe ? If so, it might make sense instead to create a docker image and build inside it.

**Comment by FireBurn** [comment]
It would be nice to have the whole binary as static, but as long as OpenSSL 1.1.1 is compiled in, to give TLS 1.3 support on RHEL7, I'll post the script that works on RHEL5 & RHEL8 tomorrow

**Comment by FireBurn** [comment]
This script works on RHEL5 & RHEL8

```shell
#!/bin/bash

PREFIX=${HOME}/haproxy
BUILD_DIR=${HOME}/build
ZLIB_VERSION=1.2.12
PCRE2_VERSION=10.40
OPENSSL_VERSION=1.1.1q
LUA_VERSION=5.4.4
HAPROXY_VERSION=2.6.1
HAPROXY_BRANCH=${HAPROXY_VERSION:0:3}

rm -rf ${BUILD_DIR}

mkdir -p ${BUILD_DIR}

cd ${BUILD_DIR}

export PKG_CONFIG_PATH=${PREFIX}/lib/pkgconfig:${PKG_CONFIG_PATH}
export LD_LIBRARY_PATH=${PREFIX}/lib/:${LD_LIBRARY_PATH}
export CFLAGS="-O3 -march=core2 -fPIE -fstack-protector-all -D_FORTIFY_SOURCE=2" 
export CXXFLAGS=${CFLAGS} 
export LDFLAGS="-Wl,-z,now -Wl,-z,relro"

wget --no-check-certificate https://zlib.net/zlib-${ZLIB_VERSION}.tar.gz
wget --no-check-certificate https://github.com/PCRE2Project/pcre2/releases/download/pcre2-${PCRE2_VERSION}/pcre2-${PCRE2_VERSION}.tar.gz
wget --no-check-certificate https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz
wget --no-check-certificate https://www.lua.org/ftp/lua-${LUA_VERSION}.tar.gz
wget --no-check-certificate http://www.haproxy.org/download/${HAPROXY_BRANCH}/src/haproxy-${HAPROXY_VERSION}.tar.gz

# Compile Zlib

tar xf zlib-${ZLIB_VERSION}.tar.gz

cd zlib-${ZLIB_VERSION}

./configure --static --prefix=${PREFIX}

make -j10

make install

cd ..

# Compile PCRE2

tar xf pcre2-${PCRE2_VERSION}.tar.gz

cd pcre2-${PCRE2_VERSION}

./configure --disable-shared --enable-jit --enable-pcregrep-jit --prefix=${PREFIX}

make -j10

make install

cd ..

# Compile OpenSSL

tar xf openssl-${OPENSSL_VERSION}.tar.gz

cd openssl-${OPENSSL_VERSION}

./config --prefix=${PREFIX} --openssldir=/etc/pki/tls/ no-shared threads

DEFAULT_CFLAGS=$(grep ^CFLAGS= Makefile | LC_ALL=C sed \
                -e 's:^CFLAGS=::' \
                -e 's:-fomit-frame-pointer ::g' \
                -e 's:-O[0-9] ::g' \
                -e 's:-march=[-a-z0-9]* ::g' \
                -e 's:-mcpu=[-a-z0-9]* ::g' \
                -e 's:-m[a-z0-9]* ::g' \
                -e 's:\\:\\\\:g' \
        )

sed -i \
        -e "/^CFLAGS=/s|=.*|=${DEFAULT_CFLAGS} ${CFLAGS}|" \
        -e "/^LDFLAGS=/s|=[[:space:]]*$|=${LDFLAGS}|" \
        Makefile || die

make -j10

make install_sw
make install_ssldirs

cd ..

# Build Lua

tar xf lua-${LUA_VERSION}.tar.gz

cd lua-${LUA_VERSION}

make CFLAGS="-O3 -march=core2 -fPIE -fstack-protector-all -D_FORTIFY_SOURCE=2" LDFLAGS="-Wl,-z,now -Wl,-z,relro -ltermcap" linux

make install INSTALL_TOP=${PREFIX} INSTALL_LIB=${PREFIX}/lib

cd ..

# Compile Haproxy

tar xf haproxy-${HAPROXY_VERSION}.tar.gz

cd haproxy-${HAPROXY_VERSION}

sed -i "s#-Wl,-Bdynamic##g" Makefile

make CFLAGS="-O3 -march=core2 \$(SPEC_CFLAGS) -fPIE -fstack-protector-all -D_FORTIFY_SOURCE=2 -DLUA_C89_NUMBERS" \
  LDFLAGS="-static -pthread -ldl" \
  TARGET=linux-glibc \
  USE_GETADDRINFO=1 \
  USE_LUA=1 \
  LUA_LIB=${PREFIX}/lib \
  LUA_INC=${PREFIX}/include \
  USE_TFO=1 \
  USE_ZLIB=1 \
  ZLIB_LIB=${PREFIX}/lib \
  ZLIB_INC=${PREFIX}/include \
  USE_STATIC_PCRE2=1 \
  USE_PCRE2_JIT=1 \
  USE_OPENSSL=1 \
  SSL_INC=${PREFIX}/include \
  SSL_LIB=${PREFIX}/lib \
  USE_NS= \
  USE_ACCEPT4= \
  USE_CPU_AFFINITY= \
  USE_LIBCRYPT=1 \
  USE_PROMEX=1 \
  PREFIX=${PREFIX} \
  -j10

make install PREFIX=${PREFIX}

cd ${PREFIX}

rm -rf bin doc include lib man share

strip sbin/* || true

tar czSf ${HOME}/haproxy-${HAPROXY_VERSION}.tar.gz *

rm -rf ${BUILD_DIR} ${PREFIX}
```

**Comment by FireBurn** [comment]
This is now the new combined RHEL6, RHEL7 & RHEL8 script where OpenSSL 1.1.1 is forced on 6 & 7


```
# Keep a note of the current working directory

export JENKINS_DIR=$(pwd)
export PREFIX=${JENKINS_DIR}/apps/haproxy
export HAPROXY_BRANCH=${HAPROXY_VERSION:0:3}

export OS_MAJOR_VERSION=`sed -rn 's/.*([0-9])\.[0-9].*/\1/p' /etc/redhat-release`

if [[ "${OS_MAJOR_VERSION}" == "8" ]]; then
  MARCH="haswell"
  NS="USE_NS=1"
  PCRE="USE_PCRE2=1 USE_PCRE2_JIT=1"
  STATIC=""
fi
if [[ "${OS_MAJOR_VERSION}" == "7" ]]; then
  MARCH="corei7-avx"
  NS="USE_NS=1"
  PCRE="USE=PCRE=1 USE_PCRE_JIT=1"
  STATIC="SSL_INC=${PREFIX}/include SSL_LIB=${PREFIX}/lib"
fi
if [[ "${OS_MAJOR_VERSION}" == "6" ]]; then
  MARCH="core2"
  NS="USE_NS="
  PCRE="USE=PCRE=1"
  STATIC="SSL_INC=${PREFIX}/include SSL_LIB=${PREFIX}/lib"
fi

# Download source files

wget --no-check-certificate https://www.openssl.org/source/openssl-${OPENSSL_VERSION}.tar.gz
wget --no-check-certificate -nv https://www.lua.org/ftp/lua-${LUA_VERSION}.tar.gz
#wget --no-check-certificate -nv http://www.haproxy.org/download/${HAPROXY_BRANCH}/src/haproxy-${HAPROXY_VERSION}.tar.gz
/apps/was/git/bin/git clone https://github.com/FireBurn/haproxy -b v${HAPROXY_VERSION}

cd haproxy

git cherry-pick 0eab050b040d4240d78e0c1eb4db937bcddc834f # BUG/MINOR: http-htx: Fix scheme based normalization for URIs wih userinfo
git cherry-pick 658f971621839f3b928da099dfe3092b47cbc958 # MINOR: http: Add function to get port part of a host
git cherry-pick ca7218aaf073627b665459bd881b2b35a481602a # MINOR: http: Add function to detect default port
git cherry-pick 3f5fbe940733bba84b5ee875af5b13aa3144aa41 # BUG/MEDIUM: h1: Improve authority validation for CONNCET request
git cherry-pick d1d983fb1267a42e602bf7fb0467e4cfa3c184de # MINOR: http-htx: Use new HTTP functions for the scheme based normalization
git cherry-pick 12f6dbb863fe941c6d84cf3d521dfcb4c0e2f355 # BUG/MEDIUM: http-fetch: Don't fetch the method if there is no stream

sed -i "s#static int httpclient_ssl_verify = SSL_SOCK_VERIFY_REQUIRED#static int httpclient_ssl_verify = SSL_SOCK_VERIFY_NONE#g" src/http_client.c

cd ..

if [[ "${OS_MAJOR_VERSION}" -le "7" ]]; then

# Build OpenSSL

tar xf openssl-${OPENSSL_VERSION}.tar.gz

cd openssl-${OPENSSL_VERSION}

CFLAGS="-O3 -march=${MARCH} -fPIE -fstack-protector-all -D_FORTIFY_SOURCE=2 -fno-strict-aliasing"
LDFLAGS="-Wl,-z,now -Wl,-z,relro"

./config --prefix=${PREFIX} --openssldir=/etc/pki/tls no-shared threads

DEFAULT_CFLAGS=$(grep ^CFLAGS= Makefile | LC_ALL=C sed \
                -e 's:^CFLAGS=::' \
                -e 's:-fomit-frame-pointer ::g' \
                -e 's:-O[0-9] ::g' \
                -e 's:-march=[-a-z0-9]* ::g' \
                -e 's:-mcpu=[-a-z0-9]* ::g' \
                -e 's:-m[a-z0-9]* ::g' \
                -e 's:\\:\\\\:g' \
        )

sed -i \
        -e "/^CFLAGS=/s|=.*|=${DEFAULT_CFLAGS} ${CFLAGS}|" \
        -e "/^LDFLAGS=/s|=[[:space:]]*$|=${LDFLAGS}|" \
        Makefile || die

make -j20

sudo chown -R wasadm:was /etc/pki/tls/

make install_sw
make install_ssldirs

cd ..

fi

# Build Lua

tar xf lua-${LUA_VERSION}.tar.gz

cd ${JENKINS_DIR}/lua-${LUA_VERSION}

make CFLAGS="-O3 -march=${MARCH} -fPIE -fstack-protector-all -D_FORTIFY_SOURCE=2 -fno-strict-aliasing -DLUA_USE_LINUX" LDFLAGS="-Wl,-z,now -Wl,-z,relro" linux

make install INSTALL_TOP=${PREFIX} INSTALL_LIB=${PREFIX}/lib

cd ..

# Compile Haproxy

#tar xf haproxy-${HAPROXY_VERSION}.tar.gz

#cd ${JENKINS_DIR}/haproxy-${HAPROXY_VERSION}
cd ${JENKINS_DIR}/haproxy

make CFLAGS="-O3 -march=${MARCH} \$(SPEC_CFLAGS) -fPIE -fstack-protector-all -fno-strict-aliasing -D_FORTIFY_SOURCE=2" \
  LDFLAGS="-Wl,-z,now -Wl,-z,relro -pthread" \
  TARGET=linux-glibc \
  USE_GETADDRINFO=1 \
  USE_LUA=1 \
  LUA_LIB=${PREFIX}/lib \
  LUA_INC=${PREFIX}/include \
  USE_TFO=1 \
  USE_ZLIB=1 \
  USE_OPENSSL=1 \
  ${PCRE} \
  ${NS} \
  USE_LIBCRYPT=1 \
  USE_PROMEX=1 \
  PREFIX=/apps/was/haproxy \
  -j10

make install DESTDIR=${JENKINS_DIR} PREFIX=/apps/was/haproxy/

cd ${PREFIX}

rm -rf bin doc include lib man share

strip sbin/* || true

./sbin/haproxy -vv

tar czSf ${JENKINS_DIR}/apps/was/haproxy-${HAPROXY_VERSION}.tar.gz *
```

**Comment by FireBurn** [comment]
The RHEL5 binary is still segfaulting when run

I think due to:

```
ed232148a7dbffbc279cb8efde3fd32c3fa94847 is the first bad commit
commit ed232148a7dbffbc279cb8efde3fd32c3fa94847
Author: David Carlier <devnexen@gmail.com>
Date:   Thu Nov 25 16:09:45 2021 +0000

    MEDIUM: pool: refactor malloc_trim/glibc and jemalloc api addition detections.
    
    Attempt to detect jemalloc at runtime before hand whether linked or via
    symbols overrides, and fall back to malloc_trim/glibc for Linux otherwise.

 src/pool.c | 62 ++++++++++++++++++++++++++++++++------------------------------
 1 file changed, 32 insertions(+), 30 deletions(-)
```

**Comment by wtarreau** [comment]
Oh that reminds me something. This one caused some trouble on Windows and MacOS that I fixed with this commit:
```
commit 781f07a62064dbaefc362c1077d6a5382a186893
Author: Willy Tarreau <w@1wt.eu>
Date:   Fri Nov 26 15:55:55 2021 +0100

    BUILD: pools: only detect link-time jemalloc on ELF platforms
    
    The build broke on Windows and MacOS after commit ed232148a ("MEDIUM:
    pool: refactor malloc_trim/glibc and jemalloc api addition detections."),
    because the extern+attribute(weak) combination doesn't result in a really
    weak symbol and it causes an undefined symbol at link time.
    
    Let's reserve this detection to ELF platforms. The runtime detection using
    dladdr() remains used if defined.
    
    No backport needed, this is purely 2.6.
```

I too remember having faced a crash when trying to access this symbol on one platform, though I don't remember what combination. Maybe it was uclibc on MIPS that I use from time to time. The problem was visible immediately when the symbol was read, a call to the dynamic linker's functions was made to retrieve the symbol's pointer and resulted in a crash as the symbol didn't exist. Could you please try to see if just enclosing that part in `#if 0` fixes it for you ? If so, I think we should only detect jemalloc via the dynamic linker:
```
diff --git a/src/pool.c b/src/pool.c
index 1d4f2dfbc..4d1d7d2ec 100644
--- a/src/pool.c
+++ b/src/pool.c
@@ -77,9 +77,11 @@ static void trim_all_pools(void)
  */
 static void detect_allocator(void)
 {
-#if defined(__ELF__)
+#if 0
        extern int mallctl(const char *, void *, size_t *, void *, size_t) __attr
 
        my_mallctl = mallctl;
 #endif
```

If that's sufficient, I'm fine with just deleting that part.

**Comment by wtarreau** [comment]
OK I can reproduce it on one of my older machines with gcc-4.4 and glibc-2.11:
```
Program received signal SIGSEGV, Segmentation fault.
0x00000000006110aa in do_sym ()
(gdb) bt
#0  0x00000000006110aa in do_sym ()
#1  0x00000000005c5b34 in dlsym_doit ()
#2  0x000000000060c3f9 in _dl_catch_error ()
#3  0x00000000005c5ca4 in _dlerror_run ()
#4  0x00000000005c5aea in __dlsym ()
#5  0x0000000000552330 in detect_allocator () at src/pool.c:160
#6  init_pools () at src/pool.c:1043
#7  0x000000000050c467 in main (argc=<value optimized out>, argv=0x7fffffffe1d8)
    at src/haproxy.c:3072
```

What I didn't expect, however, is that it dies in dlsym()!
But I think I found a way to detect at runtime if we're statically linked. Let me check.

**Comment by wtarreau** [comment]
Mike, I managed to work around the issue in glibc-2.11 with the following commit in master, could you please try it ?

  288dc1d8e ("BUG/MEDIUM: tools: avoid calling dlsym() in static builds")

**Comment by FireBurn** [comment]
Thanks, that did the trick

From now on though I'll avoid doing full static builds - all I really needed was a share build with an included static OpenSSL
